### PR TITLE
Doc: update Pull_Request template for contributor

### PR DESCRIPTION
**Pull request by tuhaihe**
See: Discussion#20 <http://github.com/orgs/cloudberrydb/discussions/20>

---

### Change logs

Update the contributor's checklist type from a bulleted list to a task list, so that contributors can check them before/when they submit PRs.

### Why are the changes needed?

For a better check to contributors.

### Does this PR introduce any user-facing change?

No, no changes to the core code.

### How was this patch tested?

_Please detail how the changes were tested, including manual tests and any relevant unit or integration tests._

### Contributor's Checklist
Here are some reminders before you submit the pull request:
* Document changes
* Communicate in the [GitHub Issues](https://github.com/cloudberrydb/cloudberrydb/issues) or [Discussions](https://github.com/orgs/cloudberrydb/discussions) (list them if needed)
* Add tests for the change
* Pass `make installcheck`
* Pass `make -C src/test installcheck-cbdb-parallel`

### CODE REVIEW

**Review by avamingli — APPROVED** [review]

**Review by my-ship-it — APPROVED** [review]

**Comment by my-ship-it** [comment]
Hi @tuhaihe Please don't use merge for first commit in your pull request. We need to keep git history linear.

**Comment by avamingli** [comment]
> Hi @tuhaihe Please don't use merge for first commit in your pull request. We need to keep git history linear.

Use rebase instead.

**Comment by tuhaihe** [comment]
Got it, thanks! @my-ship-it @avamingli

**Comment by tuhaihe** [comment]
I dropped the merge history and rebased my commit, PTAL again! @avamingli

**Pull request merged**
