### PR TITLE
Modify the orca optimizer's processing of unionall distribution strategy

### PR DESCRIPTION
**Pull request by Light-City**
### Change logs

    The orca optimizer currently returns the ANY policy for the first child of a unionall-like node, which will result in Gather Motion for the downstream children and a 1:n Redistribution for the upstream.

    for example:
```
    ->  Redistribute Motion 1:3  (slice2)
       ->  Append  (cost=0.00..863.91 rows=18001 width=12)
          ->  Finalize Vec Aggregate
            ->  Gather Motion 3:1  (slice3; segments: 3)
		...
       ->  Gather Motion 3:1  (slice4; segments: 3)
          ->  HashAggregate
```
    after:
```
    ->  Append  (cost=0.00..863.91 rows=18001 width=12)
       ->  Result  (cost=0.00..431.06 rows=1 width=12)
          ->  Redistribute Motion 1:3  (slice2)
            ->  Finalize Aggregate
               ->  Gather Motion 3:1  (slice3; segments: 3)
               ...
       ->  HashAggregate
```
When there are many nodes, the first plan will cause performance bottlenecks and need to be modified. Fortunately, the gpdb community has also modified th is. Commit is 0cd056a0a3d3c30a1d6d4479e67802b6673118c7.

### Why are the changes needed?

1.Affect performance
2.Plan is unreasonable

### Does this PR introduce any user-facing change?

yes, tpcds 167 query.

### How was this patch tested?

yes.

### Contributor's Checklist

Here are some reminders and checklists before/when submitting your pull request, please check them:

- [ ] Make sure your Pull Request has a clear title and commit message. You can take [git-commit](https://github.com/cloudberrydb/cloudberrydb/blob/main/.gitmessage) template as a reference.
- [ ] Sign the Contributor License Agreement as prompted for your first-time contribution(*One-time setup*).
- [ ] Learn the [coding contribution guide](https://cloudberrydb.org/contribute/code), including our code conventions, workflow and more.
- [ ] List your communication in the [GitHub Issues](https://github.com/cloudberrydb/cloudberrydb/issues) or [Discussions](https://github.com/orgs/cloudberrydb/discussions) (if has or needed).
- [ ] Document changes.
- [ ] Add tests for the change
- [ ] Pass `make installcheck`
- [ ] Pass `make -C src/test installcheck-cbdb-parallel`
- [ ] Feel free to @cloudberrydb/dev team for review and approval when your PR is ready🥳

### CODE REVIEW

**Comment by Light-City** [comment]
related issue is https://github.com/cloudberrydb/cloudberrydb/issues/279.

**Comment by tuhaihe** [comment]
> related issue is #279.

One tip: we can use `closes #279` here, and then after this PR is merged, the issue will be closed automatically. For more tips see the [GitHub doc](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests).

**Comment by Light-City** [comment]
> > related issue is #279.
> 
> One tip: we can use `closes #279` here, and then after this PR is merged, the issue will be closed automatically. For more tips see the [GitHub doc](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests).

ok

**Comment by my-ship-it** [comment]
After discussion, close the PR.

**Pull request closed without merging**
