### PR TITLE
Fix test artifact upload path incorrectly

### PR DESCRIPTION
**Pull request by Zhangbaowen-Hashdata**
In order to make it easier for users to quickly locate error logs, we have copied the entire directory to a fixed location and thoroughly tested it without encountering any issues.

closes: #ISSUE_Number

---

### Change logs

_Describe your change clearly, including what problem is being solved or what feature is being added._

_If it has some breaking backward or forward compatibility, please clary._

### Why are the changes needed?

_Describe why the changes are necessary._

### Does this PR introduce any user-facing change?

_If yes, please clarify the previous behavior and the change this PR proposes._

### How was this patch tested?

_Please detail how the changes were tested, including manual tests and any relevant unit or integration tests._

### Contributor's Checklist

Here are some reminders and checklists before/when submitting your pull request, please check them:

- [ ] Make sure your Pull Request has a clear title and commit message. You can take [git-commit](https://github.com/cloudberrydb/cloudberrydb/blob/main/.gitmessage) template as a reference.
- [ ] Sign the Contributor License Agreement as prompted for your first-time contribution(*One-time setup*).
- [ ] Learn the [coding contribution guide](https://cloudberrydb.org/contribute/code), including our code conventions, workflow and more.
- [ ] List your communication in the [GitHub Issues](https://github.com/cloudberrydb/cloudberrydb/issues) or [Discussions](https://github.com/orgs/cloudberrydb/discussions) (if has or needed).
- [ ] Document changes.
- [ ] Add tests for the change
- [ ] Pass `make installcheck`
- [ ] Pass `make -C src/test installcheck-cbdb-parallel`
- [ ] Feel free to @cloudberrydb/dev team for review and approval when your PR is ready🥳

### CODE REVIEW

**Comment by Zhangbaowen-Hashdata** [comment]
The commit information has been completed. I'll be happy to help you check if there are any further changes needed. @tuhaihe

**Comment by tuhaihe** [comment]
Hey @Zhangbaowen-Hashdata: I appreciate your effort, but the maximum limit for the commit body length is 72 characters instead of 50. Could you amend it again?

**Comment by Zhangbaowen-Hashdata** [comment]
> Hey @Zhangbaowen-Hashdata: I appreciate your effort, but the maximum limit for the commit body length is 72 characters instead of 50. Could you amend it again?

ok,I will make it

**Review by baotingfang — APPROVED** [review]
LGTM

**Review by tuhaihe — APPROVED** [review]
LGTM.
After this PR is merged, we can close #118.

**Review by my-ship-it — APPROVED** [review]
LGTM

**Pull request merged**
