### PR TITLE
Cherry pick gporca commits Feb152022-Mar252022

### PR DESCRIPTION
**Pull request by leborchuk**
Cherry-pick a couple of commits to gporca as suggested in https://github.com/orgs/cloudberrydb/discussions/675

Have some conflicts with https://github.com/cloudberrydb/cloudberrydb/pull/565 - fixed them manually

---

### Change logs

Here I added commits:

Mar 15, 2022 Fix Printing Expression Properties https://github.com/open-gpdb/gpdb/commit/1902fbcddcef233a683f1771a24b94badca920ec
Mar 18, 2022 Add ORCA GUC to disable NLJ https://github.com/open-gpdb/gpdb/commit/4c05173937c927d5122e0fd26900677fa9289251
Mar 18, 2022 Fix flaky qp_misc test case (#13261) https://github.com/open-gpdb/gpdb/commit/cd84fb806f24cecc584040a6420545600b67ef9d
Mar 25, 2022 Fix FNullRejecting() error while trying to process zero-placed predicate. https://github.com/open-gpdb/gpdb/commit/3ae4d19575bdd34efe8ed56c10b26dd43780bb84 - conflict with https://github.com/cloudberrydb/cloudberrydb/pull/565

### Why are the changes needed?

_Describe why the changes are necessary._

### Does this PR introduce any user-facing change?

_If yes, please clarify the previous behavior and the change this PR proposes._

### How was this patch tested?

make installcheck-world

### Contributor's Checklist

Here are some reminders and checklists before/when submitting your pull request, please check them:

- [ ] Make sure your Pull Request has a clear title and commit message. You can take [git-commit](https://github.com/cloudberrydb/cloudberrydb/blob/main/.gitmessage) template as a reference.
- [ ] Sign the Contributor License Agreement as prompted for your first-time contribution(*One-time setup*).
- [ ] Learn the [coding contribution guide](https://cloudberrydb.org/contribute/code), including our code conventions, workflow and more.
- [ ] List your communication in the [GitHub Issues](https://github.com/cloudberrydb/cloudberrydb/issues) or [Discussions](https://github.com/orgs/cloudberrydb/discussions) (if has or needed).
- [ ] Document changes.
- [ ] Add tests for the change
- [ ] Pass `make installcheck`
- [ ] Pass `make -C src/test installcheck-cbdb-parallel`
- [ ] Feel free to request `cloudberrydb/dev` team for review and approval when your PR is ready🥳

### CODE REVIEW

**Comment by my-ship-it** [comment]
Please fix CI failures.

**Comment by leborchuk** [comment]
Could you re-launch tests? Only maintainer could do this.

I downloaded icw-test.zip artifacts and checked if only gporca test failed. Then fixed it and  run make installcheck on my env and checked if gporca test does not fail anymore (miss space last time).

**Comment by tuhaihe** [comment]
hi @leborchuk hi, re-trigger the ci workflow.

**Comment by leborchuk** [comment]
See new failed checks, fixied it and checking tests

**Comment by leborchuk** [comment]
Ok, checked, everything works fine on my environment - ``qp_misc ... ok 63410 ms (diff 1617 ms)``. Could you please restart the tests again?

**Comment by tuhaihe** [comment]
Hi @leborchuk, I have invited you to join the Cloudberry org. You can trigger the failed tests again by yourself. Once the tests fail, welcome to try again!

**Comment by leborchuk** [comment]
Ok, thanks! Now all looks fine^ tests is Ok, could be reviewed once again

**Review by yjhjstz — APPROVED** [review]
LGTM

**Comment by yjhjstz** [comment]
```
[Add space to scripts regress output](https://github.com/cloudberrydb/cloudberrydb/pull/678/commits/208d3988283eb3a36bfcf58a6c31bfc609feda86)

[Fix Greenplum -> cloudberry in qp_misc.sql out](https://github.com/cloudberrydb/cloudberrydb/pull/678/commits/7cbdf0e4be782dc6750ad624a739652599fae6d1)
```
better to combine this two commits.

**Comment by leborchuk** [comment]
Yep, thanks! It's better to avoid doing meaningless commits, so I squashed test fixes in a single commit.

**Comment by tuhaihe** [comment]
Thanks @leborchuk!

It's better to have a clearer and more descriptive title for the combined commit. Currently, it is called `Fixed tests: `, which may confuse other developers when reviewing the commit history y.

```
41ac6fdd59 (HEAD -> main, upstream/main, upstream/HEAD) Fixed tests:
6a95c6391f Fix FNullRejecting() error while trying to process zero-placed predicate.
a4a0a07c2c Fix flaky qp_misc test case (#13261)
9b3bf7a65f Add ORCA GUC to disable NLJ
```

**Pull request merged**
