### PR TITLE
Restore sources' original copyright information

### PR DESCRIPTION
**Pull request by tuhaihe**
closes: #ISSUE

---

### Change logs

This PR is used for restoring Cloudberry Database codebase files' original copyright information, including cases such as `Cloudberry Inc`~>`Greenplum Inc` and more.

In addition, adding hashData license header info to the files changed initially, created, or updated by the Cloudberry Database team. 

### Why are the changes needed?

Follow the open source license.

### Does this PR introduce any user-facing change?

No.

### How was this patch tested?

_Please detail how the changes were tested, including manual tests and any relevant unit or integration tests._

### Contributor's Checklist
Here are some reminders before you submit the pull request:
* Document changes
* Communicate in the [GitHub Issues](https://github.com/cloudberrydb/cloudberrydb/issues) or [Discussions](https://github.com/orgs/cloudberrydb/discussions) (list them if needed)
* Add tests for the change
* Pass `make installcheck`
* Pass `make -C src/test installcheck-cbdb-parallel`

### CODE REVIEW

**Comment by sandiandian** [comment]
The build failed because the package name of the rpm in the .cloudberry-db.spec file was changed from cloudberry-db to cloudberrydb @tuhaihe

**Comment by tuhaihe** [comment]
hi @sandiandian , thanks for your comments. I noticed the conflicts as GitHub promotes. Let me fix this.

**Comment by my-ship-it** [comment]
Is the PR ready for ready now?

**Comment by tuhaihe** [comment]
@my-ship-it, all checks have passed. Now it's ready to approve. Thanks!

**Review by avamingli — APPROVED** [review]

**Review by my-ship-it — APPROVED** [review]

**Pull request merged**
