### PR TITLE
change `MAX_TARABLE_SYMLINK_PATH_LENGTH` to 200

### PR DESCRIPTION
**Pull request by shmiwy**
Symlink targets currently have a length limit of 100, which may not be sufficient in many test cases, so we change it to 200 here.

---

### Change logs

change MAX_TARABLE_SYMLINK_PATH_LENGTH to 200

### Why are the changes needed?

In many test cases, we found that the 100 limit was not enough.

### Does this PR introduce any user-facing change?

No

### Contributor's Checklist

Here are some reminders and checklists before/when submitting your pull request, please check them:

- [x] Make sure your Pull Request has a clear title and commit message. You can take [git-commit](https://github.com/cloudberrydb/cloudberrydb/blob/main/.gitmessage) template as a reference.
- [x] Sign the Contributor License Agreement as prompted for your first-time contribution(*One-time setup*).
- [x] Learn the [coding contribution guide](https://cloudberrydb.org/contribute/code), including our code conventions, workflow and more.
- [x] List your communication in the [GitHub Issues](https://github.com/cloudberrydb/cloudberrydb/issues) or [Discussions](https://github.com/orgs/cloudberrydb/discussions) (if has or needed).
- [x] Document changes.
- [x] Add tests for the change
- [x] Pass `make installcheck`
- [x] Pass `make -C src/test installcheck-cbdb-parallel`
- [x] Feel free to request `cloudberrydb/dev` team for review and approval when your PR is ready🥳

### CODE REVIEW

**Review by my-ship-it — APPROVED** [review]
LGTM

**Review by gfphoenix78 — APPROVED** [review]
LGTM

**Comment by my-ship-it** [comment]
Please fix CI failures.

**Comment by my-ship-it** [comment]
@shmiwy Please fix CI failures?

**Comment by my-ship-it** [comment]
After discussion with @shmiwy, close the PR.

**Pull request closed without merging**
