### PR TITLE
Fix bugs which could not create unique index "gp_fastsequence_objid_objmod_index"

### PR DESCRIPTION
**Pull request by lss602726449**
closes: #132

---

### Change logs

As indicated by the test in the issue. The same key exists in gp_fastsequence. The root cause is that a crash occurred when a tuple was inserted in gp_fastsequence in the test. Because it inserted a frozen tuple, and the tuple insertion and index update were not atomic. We can reproduce this problem by killing the server when the index is not inserted after inserting the tuple. To solve this problem, we can solve this problem by inserting a simple tuple and index (that is, the serevr crash triggers transaction rollback at this time), and after inserting the index, update it to a frozen tuple.

### Why are the changes needed?

Fix the inconsistency of index and tuple in gp_fastsequence.

### Does this PR introduce any user-facing change?

No

### How was this patch tested?

cherrypick from GPDB

### Contributor's Checklist

Here are some reminders and checklists before/when submitting your pull request, please check them:

- [x] Make sure your Pull Request has a clear title and commit message. You can take [git-commit](https://github.com/cloudberrydb/cloudberrydb/blob/main/.gitmessage) template as a reference.
- [x] Sign the Contributor License Agreement as prompted for your first-time contribution.
- [x] List your communication in the [GitHub Issues](https://github.com/cloudberrydb/cloudberrydb/issues) or [Discussions](https://github.com/orgs/cloudberrydb/discussions) (if has or needed).
- [x] Document changes.
- [x] Add tests for the change
- [x] Pass `make installcheck`
- [x] Pass `make -C src/test installcheck-cbdb-parallel`
- [x] Feel free to @cloudberrydb/dev team for review and approval when your PR is ready🥳

### CODE REVIEW

**Comment by tuhaihe** [comment]
Hi @lss602726449, Thank you for your efforts! Please revise both your pull request and commit message's title and body to ensure they are thorough and easy to understand. You can follow our [commit conventions](https://github.com/cloudberrydb/cloudberrydb/blob/main/.gitmessage) as a guide.

**Comment by yjhjstz** [comment]
root cause is ?

**Comment by lss602726449** [comment]
> 

Maybe the  root cause is geting the wrong snapshot in the reindex. So that it gets two version of the same tuple to build the unique index. So error ocuurs. And due to cannot reproduct in the lcoal computer. We try to reproduct it in the CI pipeline.

**Comment by lss602726449** [comment]
> root cause is ?

Maybe the root cause is geting the wrong snapshot in the reindex. So that it gets two version of the same tuple to build the unique index. So error ocuurs. And due to cannot reproduct in the lcoal computer. We try to reproduct it in the CI pipeline.

**Review by avamingli — APPROVED** [review]

**Review by HuSen8891 — APPROVED** [review]

**Pull request merged**
