### PR TITLE
Revert "Fix explain bad indent when showing operatorMem."

### PR DESCRIPTION
**Pull request by avamingli**
Reverts cloudberrydb/cloudberrydb#288

### CODE REVIEW

**Comment by avamingli** [comment]
ORCA has some failed.

**Comment by tuhaihe** [comment]
Hi @avamingli, For the #288 checks failing, the [job](https://github.com/cloudberrydb/cloudberrydb/actions/runs/6768777046/job/18394314320) also showed when `setuping upterm session`, `sudo: apt-get: command not found`. I'm not sure if the workflow should be updated too. Just FYI.

**Comment by avamingli** [comment]
> Hi @avamingli, For the #288 checks failing, the [job](https://github.com/cloudberrydb/cloudberrydb/actions/runs/6768777046/job/18394314320) also showed when `setuping upterm session`, `sudo: apt-get: command not found`. I'm not sure if the workflow should be updated too. Just FYI.

I see this on other prs too, May need help from @smartyhero

**Review by my-ship-it — APPROVED** [review]
LGTM

**Review by gfphoenix78 — APPROVED** [review]
+1

**Pull request merged**
